### ISSUE TITLE
Error=Unable to validate account; status=401: Unauthorized

### ISSUE THREAD

**Issue by VidarDev** [gitkraken/vscode-gitlens#1911]
Unable to sign in to your GitLens+ account. Please try again. If this issue persists, please contact support. Account=VidarDev 

I have trial but it dont work and on public repoistorys too

**Comment by winstonhenke** [comment]
Also having this issue.
macOS Monterey: 12.3
VS Code: Version: 1.65.2 - Commit: `c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1`

When version 12 first came out I was able to signup for GitLens+ and authenticate the extension in VS Code, but every time I try to update the extension past `v12.0.1` I'm not able to sign in to GitLens+ and I see this error message and the following log snippet
<img width="462" alt="Screen Shot 2022-03-20 at 11 35 09 AM" src="https://user-images.githubusercontent.com/7953636/159172740-3d7b5157-bbb5-4f86-9355-3f04120b24cd.png">

```log
[2022-03-20 16:29:38.554] ClientRequest.<anonymous>
FetchError: request to https://api.gitkraken.com/gitlens/checkin failed, reason: connect EADDRNOTAVAIL 127.0.0.1 - Local (0.0.0.0:50008)
[2022-03-20 16:29:38.554] Object.checkInAndValidateCore
Error: Unable to validate account; status=undefined: undefined
```

If I downgrade the extension and install `v12.0.1` again then it works. I actually don't even need to sign in again then, it recognizes that I already have.

**Comment by winstonhenke** [comment]
Also tried

- Logging out of the extension
- Uninstalling the extension
- Re installing the latest version
- Still no dice. Reverting it back to v12.0.1 fixed it for me again

**Comment by eamodio** [comment]
@winstonhenke From that error (and that things work in 12.0.1 which didn't have proxy support) it seems that GitLens is trying to use a configured proxy server. Do you have a proxy server configured in VS Code or in your shell environment?

GitLens honors the VS Code `http.proxySupport` support setting which you set to `'off'` to disable any proxy support. Or if you want to do it explicitly for GitLens you can set `"gitlens.proxy": { "url": null }`.

If you try setting one of those does it resolve the issue?

**Comment by winstonhenke** [comment]
@eamodio well holy moly that worked. I have no idea why I ever changed `http.proxySupport` in the first place but that was my issue. Thanks.
